### ISSUE TITLE
Upgrade to clang-format-11 (and friends)

### ISSUE THREAD

**Issue by cajun-rat** [uptane/aktualizr#53]
At the moment Aktualizr uses clang-format-10 for formatting. We have to stick to one release to avoid different versions 'fighting' each other.

Debian Stable [is currently on clang-format-11](https://packages.debian.org/search?keywords=clang-format-11&searchon=names&suite=all&section=all), but doesn't ship clang-format-10 which motivated me to look at an upgrade. 

Aktualizr uses Ubuntu Focal (I think) for formatting checks, which has [has clang-format-11](https://packages.ubuntu.com/focal-updates/clang-format-11).

From my initial trials, the only formatting that has changed is that `Args &&... args` will drop the second space to become `Args &&...args`

**Comment by pattivacek** [comment]
> From my initial trials, the only formatting that has changed is that Args &&... args will drop the second space to become Args &&...args

Correct. And there are no changes from `clang-format-11` and `clang-format-12` by default. I don't particularly like the args change, and it's really annoying that there's no option for controlling it, and it's explicitly backwards-incompatible, so once we upgrade, anyone using older versions will conflict with the new version. Pretty bad work there, which is not usually what I expect from clang. (See [here](https://stackoverflow.com/questions/65964384/how-to-make-clang-format-11-put-a-space-after-variadic-template-decleration) for some further insight.)

Anyway, at this point, it sounds like less of a pain to just upgrade and deal with it, since it's now causing problems to not upgrade.
